### ISSUE TITLE
[BUG]: Hero Icon ChevronDownSolid  does not exist

### ISSUE THREAD

**Issue by PlkMarudny** [shinokada/flowbite-svelte-starter#1]
### Description of the bug

Not working, icon ChevronDownSolid missing

### Steps To Reproduce

Use the clone method from the documentation, ChevronDownSolid not exported from  svelte-heros@2.2.3

### Additional Information

![image](https://user-images.githubusercontent.com/4361591/171615569-b79e9d6f-b851-477b-9d37-19e69d226e48.png)

**Comment by shinokada** [comment]
Hi,
Thank you for taking time to report the bug.

Svelte-heros has changed naming. Please use ChevronDown. [Svelte-Heros](https://github.com/shinokada/svelte-heros#variation).

Please update Flowbite-Svelte:

```
npm i -D flowbite-svelte@latest
```

I also update the [doc](https://flowbite-svelte.com/accordions/icon-accordion).

Please let me know if you find more bugs.
Thank you again.
