### ISSUE TITLE
[BUG]: "svelte-kit dev" is replaced by "vite dev"

### ISSUE THREAD

**Issue by kuchaguangjie** [shinokada/flowbite-svelte-starter#2]
### Description of the bug

> svelte-kit dev is no longer available — use vite dev instead
  1. Install vite as a devDependency with npm/pnpm/etc
  2. Create a vite.config.js with the @sveltejs/kit/vite plugin (see below)
  3. Update your package.json scripts to reference `vite dev` instead of `svelte-kit dev`

### Steps To Reproduce

`pnpm run dev`

**Comment by kuchaguangjie** [comment]
This happened after svelte-kit upgration, which use vite 3.0.

**Comment by shinokada** [comment]
I updated all dependencies. Please check and let me know.

**Comment by kuchaguangjie** [comment]
Seems working now:

![starter](https://user-images.githubusercontent.com/4230959/180123128-194efac8-8004-48c0-8701-a2a26cc60888.jpg)

BTW, the port become 5173 now, it used to be 3000 (I think), you may set in `package.json`:

> "dev": "vite dev --host --port 3000",

**Comment by shinokada** [comment]
Thank you. I will set it the port number.
