### ISSUE TITLE
[BUG]: demo page is down

### ISSUE THREAD

**Issue by alexander-mart** [shinokada/flowbite-svelte-starter#4]
### Description of the bug

https://flowbite-svelte-starter.vercel.app/

```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: arn1::xct4z-1676756921789-f73faeebfb21
```

### Steps To Reproduce

Go to this page and see 404 error.

**Comment by shinokada** [comment]
Thanks. Fixed.
https://flowbite-svelte-starter.vercel.app//
