### ISSUE TITLE
[BUG]: Demo app does not correspond to current source

### ISSUE THREAD

**Issue by AngeloAnolin** [shinokada/flowbite-svelte-starter#5]
### Description of the bug

Viewing the [source code](https://github.com/shinokada/flowbite-svelte-starter) and the [current demo](https://flowbite-svelte-starter.vercel.app/), there are missing routes / pages / components.
- `pages/about`
- `pages/services`
- `pages/projects`

![image](https://github.com/shinokada/flowbite-svelte-starter/assets/1944084/94898cce-c00e-41ef-9c55-ed49b15b8fa0)

### Steps To Reproduce

- Download and run the source from this repository
- Notice the routes and some pages are missing

**Comment by shinokada** [comment]
It's a starter. You can find the demo code in jaco branch, https://github.com/shinokada/flowbite-svelte-starter/tree/jaco
